[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_curd = "4rVANt2eVBVUpPE7d6EfBHcWRX81KjoeNJ389N5ZvNrh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/to4to/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
